### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ghost** [NarutoUA/resamp-client#7]
After loading screen.

Crash message:
ReSA:MP 0.3.7 (Build 814)
Exception At Address: 0x03F8D9C6
Base: 0x03F20000

Registers:
EAX: 0x03FC5800	EBX: 0x0028FD80	ECX: 0x0028FD84	EDX: 0x00000000
ESI: 0x00000000	EDI: 0x0000000C	EBP: 0x0028FD78	ESP: 0x0028FD40
EFLAGS: 0x00210246

Stack:
+0000: 0x0000001A   0x0D446EC8   0x00000000   0x00000001
+0010: 0x00000000   0x03FC58AB   0x00000000   0x0028FD84
+0020: 0x0028FD40   0x0028F914   0x0028FF78   0x03FABF2C
+0030: 0x03FDB368   0x00000000   0x75C67D59   0x03F8189D
+0040: 0x03FC58A8   0x03FC5BFC   0x03F9C364   0x00000001
+0050: 0x03F93C2E   0x03F926C6   0x00000001   0x0053EB17
+0060: 0x442AC000   0x43C00000   0x0053ECC2   0x00000001
+0070: 0x00619B71   0x0000001A   0x00000001   0x00000001
+0080: 0x00000000   0x00748DA0   0x0000001A   0x00000001
+0090: 0x77611245   0x00000000   0x0028FF88   0x7EFDE000
+00A0: 0x01660000   0x4EBF5DE8   0x01661130   0x00000008
+00B0: 0x00000100   0x00000008   0x00000102   0x442AC000
+00C0: 0x43C00000   0x00000000   0x00000000   0x00000556
+00D0: 0x00000300   0x00000000   0x00000001   0x00170866
+00E0: 0x00000200   0x00000000   0x018002AB   0x0096A8EE
+00F0: 0x000002AB   0x00000180   0x00000020   0x0028FE20
+0100: 0x00825EA4   0x77611245   0x00000000   0x7EFDE000
+0110: 0xFFFFFFFF   0x00821D17   0x00000065   0x00000065
+0120: 0x0028FF88   0x008246F1   0x00400000   0x00000000
+0130: 0x01903C6C   0x00000000   0x00000094   0x00000006
+0140: 0x00000001   0x00001DB1   0x00000002   0x76726553
+0150: 0x20656369   0x6B636150   0x00003120   0x00000000
+0160: 0x00000000   0x00000000   0x00000000   0x00000000
+0170: 0x00000000   0x00000000   0x00000000   0x00000000
+0180: 0x00000000   0x00000000   0x00000000   0x00000000
+0190: 0x00000000   0x00000000   0x00000000   0x00000000
+01A0: 0x00000000   0x00000000   0x00000000   0x00000000
+01B0: 0x00000000   0x00000000   0x00000000   0x00000000
+01C0: 0x00000000   0x00000000   0x00824588   0x00000000
+01D0: 0x00000000   0x7EFDE000   0xC0000005   0x00000000
+01E0: 0x01903C6C   0x00000044   0x01934678   0x019379B0
+01F0: 0x01935560   0x00000000   0x00000000   0x00000000
+0200: 0x00000000   0x00000000   0x00000000   0x00000000
+0210: 0x00000000   0x00000000   0x00000000   0xFFFFFFFF
+0220: 0xFFFFFFFF   0xFFFFFFFF   0x00000000   0x00000000
+0230: 0x0028FE78   0x0028F914   0x0028FFC4   0x00825EA4
+0240: 0x00888078   0x00000000   0x0028FF94   0x7761343D
+0250: 0x7EFDE000   0x0028FFD4   0x77BA9832   0x7EFDE000
+0260: 0x777950BE   0x00000000   0x00000000   0x7EFDE000
+0270: 0x00000000   0x00000000   0x00000000   0x0028FFA0

SCM Op: 0x4ED, lDbg: 0 LastRendObj: 0
Game Version: US 1.0
State Information: L: 0  N: 0

Debugger message:
Unhandled exception at address 0x03F8D9C6 (samp.dll) in gta_sa.exe: 0xC0000005: Access violation when writing to address 0x00469EF5.

Crash address:
03F8D9C6  mov         word ptr ds:[469EF5h],0D2FFh

**Comment by NarutoUA** [comment]
Have you removed all SA:MP mods (s0beit, sampfuncs, antistealer etc) ?

**Comment by NarutoUA** [comment]
Fixed in 815 build
